[package]
name = "anyhttp"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.3.1"
reqwest = { version = "0.12.24", features = ["blocking"] }
async-trait = "0.1.89"
http-body-util = "0.1.3"
url = "2.5.7"

anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["full"] }
